apiVersion: apps/v1
kind: Service
metadata:
  name: express-ts-1
spec:
  selector:
    matchLabels:
      app: express-ts-1
  ports:
    - name: express-ts-1
      protocol: TCP
      port: 4000
      targetPort: 4000