name: deploy-service-1

on:
  push:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cd express-ts-1 && docker build -t gautamcvernekar/express-ts-1 .
    - uses: docker/login-action@v4
    - with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push gautamcvernekar/express-ts-1
