name: deploy-service-1

on:
  push:
    branches: 
      - main
    paths:
      - 'express-ts-1/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cd express-ts-1 && docker build -t gautamcvernekar/express-ts-1 .
