name: deploy-service-1

on:
  push:
    branches: 
      - main
    paths:
      - 'express-ts-1/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cd express-ts-1 && docker build -t gautamcvernekar/express-ts-1 .
    - run: docker login -u $DOCKER_USERNAME p $DOCKER_PASSWORD
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push gautamcvernekar/express-ts-1
